rules:
  # Ignore "slave" - the relation interface name for agents use this terminology.
  - name: slave
  # Ignore whitelist - we are using it to ignore pydantic in pyptoject.toml
  - name: whitelist
