name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  comment-on-pr:
    permissions:
      packages: read
      pull_requests: write
    uses: canonical/operator-workflows/.github/workflows/comment.yaml@fix/permissions
    secrets: inherit
